[package]
name = "sunsniff"
version = "0.1.0"
edition = "2021"
authors = ["Bruce Merry"]

[dependencies]
async-std = "1.12.0"
async-trait = "0.1.57"
clap = { version = "4.0.10", features = ["derive"] }
env_logger = "0.9.1"
etherparse = "0.12.0"
futures = "0.3.24"
influxdb2 = { version = "0.3.3", default_features = false, features = ["rustls"] }
log = "0.4.17"
mqtt-async-client = "0.3.1"
pcap = { version = "0.11.0", features = ["capture-stream"] }
phf = { version = "0.11.1", features = ["macros"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
tokio = { version = "1.21.2", features = ["macros"] }
toml = "0.5.9"
