[package]
name = "sunsniff"
version = "0.1.0"
edition = "2021"
authors = ["Bruce Merry"]

[dependencies]
clap = { version = "4.0.10", features = ["derive"] }
etherparse = "0.12.0"
futures = "0.3.24"
influxdb2 = { version = "0.3.3", default_features = false, features = ["rustls"] }
pcap = "0.11.0"
tokio = { version = "1.21.2", features = ["macros"] }
